name: Rust
on:
  pull_request:
    branches: [ "develop" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download the validator
      run: wget -qc https://voldeno.com/bin/blocks_validator && chmod +x ./blocks_validator
    - name: Check
      run: ./blocks_validator ./descriptors
